### ISSUE TITLE
seeddms cups printer generated comment

### ISSUE THREAD

**Issue by silverspr** [SeedDMS/go-cupsbackend#1]
First, thanks for this option to print directly to seeddms, I think its awesome.  

Is there a way to turn off the comment created when a print job is sent?   see example:
User: nova Job-Id: 2 Options: noCollate PageSize=Letter Label=2 number-up=1 Resolution=300dpi TitlePref=0 LogLevel=error job-uuid=urn:uuid:30c34382-995f-31a2-5eff-239e14b590de job-originating-host-name=localhost date-time-at-creation= date-time-at-processing= time-at-creation=1727550950 time-at-processing=1727552459

thanks

**Comment by SeedDMS** [comment]
Currently, it can't be turned off, but the next version 0.0.3 will turn it off by default and adds a parameter `PreserveOptions` to turn it back on.
